# Generated by Django 4.0.1 on 2022-01-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adset_name', models.CharField(max_length=300, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=300, unique=True)),
                ('client_comm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('client_logo', models.CharField(max_length=300, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_cost', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('adset_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_cost', to='clients.adset')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_revenue', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('adset_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_revenue', to='clients.adset')),
            ],
        ),
        migrations.CreateModel(
            name='DailyImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_impressions', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('adset_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_impressions', to='clients.adset')),
            ],
        ),
        migrations.CreateModel(
            name='DailyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_conversions', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('adset_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_conversions', to='clients.adset')),
            ],
        ),
        migrations.CreateModel(
            name='DailyClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_clicks', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('adset_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_clicks', to='clients.adset')),
            ],
        ),
        migrations.AddField(
            model_name='adset',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adset_name', to='clients.client'),
        ),
    ]
